#!/usr/bin/env node
/**
 * ChitBox Database Setup Script
 *
 * Phase 1 — Provision: creates the role and database via the postgres superuser
 *            (skipped gracefully when superuser access is unavailable).
 * Phase 2 — Schema:    applies all tables, indexes, and the email-queue tables
 *            against the chitbox database using the app credentials.
 *
 * Usage:
 *   node setup-db.js            # full setup (provision + schema)
 *   node setup-db.js --schema   # schema only (skip provision)
 *   node setup-db.js --reset    # DROP all tables first, then recreate
 */

'use strict';

const { Client } = require('pg');
const path = require('path');
const fs = require('fs');
require('dotenv').config({ path: path.join(__dirname, '.env') });

// ─── Configuration ───────────────────────────────────────────────────────────

const APP_DB     = process.env.DB_NAME     || 'chitbox';
const APP_USER   = process.env.DB_USER     || 'chitbox_user';
const APP_PASS   = process.env.DB_PASSWORD || 'ChitBox2025Secure!';
const DB_HOST    = process.env.DB_HOST     || 'localhost';
const DB_PORT    = parseInt(process.env.DB_PORT || '5432', 10);

const ARGS   = new Set(process.argv.slice(2));
const RESET  = ARGS.has('--reset');
const SCHEMA_ONLY = ARGS.has('--schema');

// ─── Helpers ─────────────────────────────────────────────────────────────────

function log(msg)  { console.log(msg); }
function ok(msg)   { console.log(`  ✅  ${msg}`); }
function info(msg) { console.log(`  ℹ️   ${msg}`); }
function warn(msg) { console.warn(`  ⚠️   ${msg}`); }
function fail(msg) { console.error(`  ❌  ${msg}`); }

async function runSQL(client, sql, description) {
  try {
    await client.query(sql);
    if (description) ok(description);
  } catch (err) {
    throw new Error(`${description || 'SQL'} failed: ${err.message}`);
  }
}

// ─── Phase 1: Provision role + database ──────────────────────────────────────

async function provision() {
  log('\n━━━ Phase 1: Provisioning role and database ━━━\n');

  const client = new Client({
    host: DB_HOST,
    port: DB_PORT,
    database: 'postgres',
    user: process.env.PGUSER || 'postgres',
    password: process.env.PGPASSWORD || '',
    connectionTimeoutMillis: 5000,
  });

  try {
    await client.connect();
    ok('Connected as postgres superuser');

    // Create role if not exists
    const roleExists = await client.query(
      `SELECT 1 FROM pg_roles WHERE rolname = $1`, [APP_USER]
    );
    if (roleExists.rowCount === 0) {
      await runSQL(
        client,
        `CREATE ROLE "${APP_USER}" WITH LOGIN PASSWORD '${APP_PASS.replace(/'/g, "''")}'`,
        `Role "${APP_USER}" created`
      );
    } else {
      // Ensure password is current
      await client.query(
        `ALTER ROLE "${APP_USER}" WITH PASSWORD '${APP_PASS.replace(/'/g, "''")}'`
      );
      info(`Role "${APP_USER}" already exists — password refreshed`);
    }

    // Create database if not exists
    const dbExists = await client.query(
      `SELECT 1 FROM pg_database WHERE datname = $1`, [APP_DB]
    );
    if (dbExists.rowCount === 0) {
      await runSQL(
        client,
        `CREATE DATABASE "${APP_DB}" OWNER "${APP_USER}" ENCODING 'UTF8'`,
        `Database "${APP_DB}" created`
      );
    } else {
      info(`Database "${APP_DB}" already exists`);
    }

    // Grants
    await client.query(`GRANT ALL PRIVILEGES ON DATABASE "${APP_DB}" TO "${APP_USER}"`);
    ok(`Privileges granted on "${APP_DB}" to "${APP_USER}"`);

  } catch (err) {
    warn(`Superuser provisioning skipped: ${err.message}`);
    info('Assuming role and database already exist — continuing to schema phase.');
  } finally {
    await client.end().catch(() => {});
  }
}

// ─── Phase 2: Apply schema ────────────────────────────────────────────────────

const RESET_SQL = `
-- Drop all ChitBox tables in dependency-safe order
DROP TABLE IF EXISTS email_delivery_logs  CASCADE;
DROP TABLE IF EXISTS email_queue          CASCADE;
DROP TABLE IF EXISTS attachments          CASCADE;
DROP TABLE IF EXISTS mail_messages        CASCADE;
DROP TABLE IF EXISTS mail_threads         CASCADE;
DROP TABLE IF EXISTS folders              CASCADE;
DROP TABLE IF EXISTS user_sessions        CASCADE;
DROP TABLE IF EXISTS users                CASCADE;
`;

const SCHEMA_SQL = `
-- ══════════════════════════════════════════════════════
--  ChitBox — Full Database Schema
--  Generated by setup-db.js — do not edit manually
-- ══════════════════════════════════════════════════════

-- ── users ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id            SERIAL        PRIMARY KEY,
    email         VARCHAR(255)  UNIQUE NOT NULL,
    name          VARCHAR(255)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    avatar_url    VARCHAR(500),
    age           INTEGER,
    profession    VARCHAR(100),
    country       VARCHAR(100),
    interests     TEXT[],
    newsletter    BOOLEAN       DEFAULT FALSE,
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN users.age        IS 'User age (13–120)';
COMMENT ON COLUMN users.profession IS 'User profession or job title';
COMMENT ON COLUMN users.interests  IS 'Array of user interest topics';
COMMENT ON COLUMN users.country    IS 'User country of residence';
COMMENT ON COLUMN users.newsletter IS 'Whether user subscribed to newsletter';

-- ── folders ──────────────────────────────────────────
-- Rows are inserted per-user when a user registers (see auth route).
CREATE TABLE IF NOT EXISTS folders (
    id         SERIAL       PRIMARY KEY,
    user_id    INTEGER      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name       VARCHAR(100) NOT NULL,
    type       VARCHAR(50)  NOT NULL,  -- inbox | sent | drafts | spam | trash | custom
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── mail_threads ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS mail_threads (
    id           SERIAL       PRIMARY KEY,
    subject      VARCHAR(500),
    folder_id    INTEGER      REFERENCES folders(id) ON DELETE CASCADE,
    user_id      INTEGER      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_read      BOOLEAN      DEFAULT FALSE,
    is_starred   BOOLEAN      DEFAULT FALSE,
    is_important BOOLEAN      DEFAULT FALSE,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── mail_messages ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS mail_messages (
    id          SERIAL       PRIMARY KEY,
    thread_id   INTEGER      NOT NULL REFERENCES mail_threads(id) ON DELETE CASCADE,
    from_email  VARCHAR(255) NOT NULL,
    from_name   VARCHAR(255),
    to_emails   TEXT[],
    cc_emails   TEXT[],
    bcc_emails  TEXT[],
    subject     VARCHAR(500),
    body_text   TEXT,
    body_html   TEXT,
    is_read     BOOLEAN      DEFAULT FALSE,
    is_draft    BOOLEAN      DEFAULT FALSE,
    is_sent     BOOLEAN      DEFAULT FALSE,
    sent_at     TIMESTAMP,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── attachments ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS attachments (
    id            SERIAL       PRIMARY KEY,
    message_id    INTEGER      NOT NULL REFERENCES mail_messages(id) ON DELETE CASCADE,
    filename      VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    mime_type     VARCHAR(100) NOT NULL,
    file_size     INTEGER      NOT NULL,
    file_path     VARCHAR(500) NOT NULL,
    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── user_sessions ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_sessions (
    id            SERIAL       PRIMARY KEY,
    user_id       INTEGER      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_token VARCHAR(255) UNIQUE NOT NULL,
    expires_at    TIMESTAMP    NOT NULL,
    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── email_queue ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS email_queue (
    id           SERIAL       PRIMARY KEY,
    from_email   VARCHAR(255) NOT NULL,
    from_name    VARCHAR(255) NOT NULL,
    to_email     VARCHAR(255) NOT NULL,
    subject      VARCHAR(500) NOT NULL,
    body_text    TEXT         NOT NULL,
    body_html    TEXT,
    cc_emails    TEXT[],
    bcc_emails   TEXT[],
    attachments  JSONB,
    status       VARCHAR(20)  DEFAULT 'pending',  -- pending | sent | failed | retrying
    attempts     INTEGER      DEFAULT 0,
    max_attempts INTEGER      DEFAULT 3,
    last_attempt TIMESTAMP,
    error_message TEXT,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    sent_at      TIMESTAMP
);

-- ── email_delivery_logs ───────────────────────────────
CREATE TABLE IF NOT EXISTS email_delivery_logs (
    id              SERIAL       PRIMARY KEY,
    email_queue_id  INTEGER      NOT NULL REFERENCES email_queue(id) ON DELETE CASCADE,
    message_id      VARCHAR(255),
    status          VARCHAR(50),   -- sent | delivered | bounced | failed
    provider_response TEXT,
    timestamp       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ══════════════════════════════════════════════════════
--  Indexes
-- ══════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_users_age                    ON users(age);
CREATE INDEX IF NOT EXISTS idx_users_profession             ON users(profession);
CREATE INDEX IF NOT EXISTS idx_users_country                ON users(country);

CREATE INDEX IF NOT EXISTS idx_folders_user_id              ON folders(user_id);

CREATE INDEX IF NOT EXISTS idx_mail_threads_user_id         ON mail_threads(user_id);
CREATE INDEX IF NOT EXISTS idx_mail_threads_folder_id       ON mail_threads(folder_id);
CREATE INDEX IF NOT EXISTS idx_mail_threads_updated_at      ON mail_threads(updated_at);

CREATE INDEX IF NOT EXISTS idx_mail_messages_thread_id      ON mail_messages(thread_id);
CREATE INDEX IF NOT EXISTS idx_mail_messages_from_email     ON mail_messages(from_email);
CREATE INDEX IF NOT EXISTS idx_mail_messages_created_at     ON mail_messages(created_at);

CREATE INDEX IF NOT EXISTS idx_attachments_message_id       ON attachments(message_id);

CREATE INDEX IF NOT EXISTS idx_user_sessions_token          ON user_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id        ON user_sessions(user_id);

CREATE INDEX IF NOT EXISTS idx_email_queue_status           ON email_queue(status);
CREATE INDEX IF NOT EXISTS idx_email_queue_created_at       ON email_queue(created_at);
CREATE INDEX IF NOT EXISTS idx_email_queue_last_attempt     ON email_queue(last_attempt);
CREATE INDEX IF NOT EXISTS idx_email_queue_to_email         ON email_queue(to_email);

CREATE INDEX IF NOT EXISTS idx_email_delivery_logs_queue_id ON email_delivery_logs(email_queue_id);
CREATE INDEX IF NOT EXISTS idx_email_delivery_logs_status   ON email_delivery_logs(status);
`;

async function applySchema() {
  log('\n━━━ Phase 2: Applying schema ━━━\n');

  const client = new Client({
    host:     DB_HOST,
    port:     DB_PORT,
    database: APP_DB,
    user:     APP_USER,
    password: APP_PASS,
    connectionTimeoutMillis: 10000,
  });

  await client.connect();
  ok(`Connected to "${APP_DB}" as "${APP_USER}"`);

  try {
    // Optional: grant schema ownership (needed when DB was created by postgres superuser)
    await client.query(
      `GRANT ALL ON SCHEMA public TO "${APP_USER}"`
    ).catch(() => {}); // non-fatal if already granted

    if (RESET) {
      warn('--reset flag detected — dropping all existing tables…');
      await runSQL(client, RESET_SQL, 'All tables dropped');
    }

    await runSQL(client, SCHEMA_SQL, 'All tables and indexes created');

    // Verify by listing tables
    const result = await client.query(`
      SELECT tablename
      FROM   pg_tables
      WHERE  schemaname = 'public'
      ORDER  BY tablename
    `);

    log('\n  Tables in database:\n');
    result.rows.forEach(r => log(`    • ${r.tablename}`));
    log('');

  } finally {
    await client.end().catch(() => {});
  }
}

// ─── Entry point ─────────────────────────────────────────────────────────────

(async () => {
  log('\n╔══════════════════════════════════════╗');
  log('║   ChitBox — Database Setup           ║');
  log('╚══════════════════════════════════════╝\n');

  if (RESET)       info('Mode: RESET  (drop + recreate)');
  else if (SCHEMA_ONLY) info('Mode: SCHEMA ONLY');
  else             info('Mode: FULL SETUP (provision + schema)');

  try {
    if (!SCHEMA_ONLY) {
      await provision();
    }
    await applySchema();

    log('╔══════════════════════════════════════╗');
    log('║   ✅  Database setup complete!       ║');
    log('╚══════════════════════════════════════╝\n');
    log('  Start the app with:');
    log('    cd /home/robustrix/htdocs/chitbox');
    log('    npm run dev:backend\n');

  } catch (err) {
    fail(err.message);
    process.exit(1);
  }
})();
